name: Headless Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run dev 
          browser: chrome
          headless: true
          wait-on: http://localhost:5000
